title: 清风徐来
description: 把复杂技术，写成可以慢慢读懂的札记
url: "https://asilencer.github.io"
baseurl: ""
timezone: Asia/Shanghai
lang: zh-CN

author:
  name: Asilencer
  email: 1635494872@qq.com
  github: Asilencer
  role: Developer
  avatar: "/assets/img/avatar.jpg"

comments:
  provider: utterances
  repo: "Asilencer/asilencer.github.io"
  issue_term: pathname
  label: discussion
  theme_light: github-light

analytics:
  busuanzi: true

theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Asilencer"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
